<?php

namespace app\api\controller;

/**
 * 发送微信消息控制器
 * Class SendWxMessage
 * @package app\api\controller
 */
class SendWxMessage extends Controller
{
    protected $user;

    /**
     * 构造方法
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->user = $this->getUser();
    }

    /**
     * 发送预约成功通知消息
     * @param $postData
     * @return mixed
     */
    protected function sendBookingMessage($postData)
    {
        $url = 'https://api.weixin.qq.com/cgi-bin/message/wxopen/template/send?access_token=' . $this->accesstoken();
        $dataArr = [];
        $dataArr['touser'] = $this->user['open_id'];
        $dataArr['form_id'] = $postData['form_id'];
        $dataArr['template_id'] = 'MmrJWgxej-plO2DRKMq03ex0MzuSFBzLAhT_HqU521M';
        $dataArr['data'] = [
            'keyword1' => [
                'value' => '123'
            ],
            'keyword2' => [
                'value' => '123'
            ],
            'keyword3' => [
                'value' => '123'
            ],
            'keyword4' => [
                'value' => '123'
            ],
//            'keyword5' => [
//                'value' => '123'
//            ],
//            'keyword6' => [
//                'value' => '123'
//            ],
        ];
        return https_curl_json($url, $dataArr, 'json');
    }

}