<?php

namespace app\api\controller;
use app\api\model\DistUser as DistUserModel;
use app\api\model\DistUserRelation as DistUserRelationModel;

/**
 * 分销会员控制器
 * Class DistUser
 * @package app\api\controller
 */
class DistUser extends Controller
{
    /* @var \app\api\model\User $user */
    private $user;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->user = $this->getUser();   // 用户信息
    }

    /**
     * 分销会员注册
     * @return array
     */
    public function register()
    {
        $model = new DistUserModel;
        $model->register($this->request->post());
        return $this->renderSuccess([], '注册成功');
    }

    /**
     * 绑定分销好友关系
     * @return array
     */
    public function bindFriRelation()
    {
        $model = new DistUserRelationModel;
        $model->bindFriRelation($this->request->post(), $this->user);
        return $this->renderSuccess();
    }

    /**
     * 我的好友列表
     * @return array
     */
    public function getFriList()
    {
        $model = new DistUserRelationModel;
        $list = $model->getFriList($this->user['dist_user_id']);
        return $this->renderSuccess(compact('list'));
    }

    /**
     * 生成分销二维码
     * @return string
     */
    public function createQrCode()
    {
        vendor('qrcode.phpqrcode');
        $value = 'http://www.baidu.com' . '&dist_user_id=' . $this->user['dist_user_id'];//二维码内容
        $errorCorrectionLevel = 'L';            //容错级别
        $matrixPointSize = 6;                   //生成图片大小
        $imageName = 'qrcode_' . $this->user['dist_user_id'] . '.png';
        \QRcode::png($value, $imageName, $errorCorrectionLevel, $matrixPointSize, 2);
        return $this->renderSuccess(compact('imageName'));
    }
}